### ISSUE TITLE
run_pycistarget: TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by DHelix** [aertslab/pycistarget#13]
**Describe the bug**
Hi! 
I received the following error when running `run_pycistarget` with a region_sets that only contained one key:value pair. It worked if there were more than one pair. 
Thanks in advance!!

**To Reproduce**
The region_sets contains one element.

```
region_sets
{'DARs': {'M2VsRest': +--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int32)   | (int32)   |
|--------------+-----------+-----------|
| chr1         | 226608679 | 226608963 |
| chr1         | 27855704  | 27856210  |
| chr1         | 28351339  | 28351652  |
| chr1         | 44318391  | 44318636  |
| ...          | ...       | ...       |
| chrX         | 3712644   | 3714014   |
| chrX         | 21940035  | 21941071  |
| chrX         | 43653999  | 43655624  |
| chrX         | 134459548 | 134460889 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,245 rows and 3 columns from 23 chromosomes.
For printing, the PyRanges was sorted on Chromosome.}}
```
```
run_pycistarget(
...     region_sets=region_sets,
...     species='homo_sapiens',
...     save_path=os.path.join(OUTPUT_DIR, 'scATAC/motifs'),
...     ctx_db_path=RANKINGS_DB_FNAME,
...     dem_db_path=SCORES_DB_FNAME,
...     path_to_motif_annotations=MOTIF_ANNOTATIONS_FNAME,
...     run_without_promoters=True,
...     n_cpu=10,
...     annotation_version='v10nr_clust',
... )
```

**Error output**
```
2022-11-01 14:08:39,977 pycisTarget_wrapper INFO     /projects/marralab_prj/djin_marralab_prj/10X_Multiome/python/2022.10.26_SCENICplus/output/scATAC/motifs folder already exists.
2022-11-01 14:08:40,795 pycisTarget_wrapper INFO     Loading cisTarget database for DARs
2022-11-01 14:08:40,795 cisTarget    INFO     Reading cisTarget database
2022-11-01 14:09:16,650 pycisTarget_wrapper INFO     Running cisTarget for DARs
2022-11-01 14:09:29,468 INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
(ctx_internal_ray pid=171608) 2022-11-01 14:09:35,577 cisTarget    INFO     Running cisTarget for M2VsRest which has 6134 regions
(ctx_internal_ray pid=171608) 2022-11-01 14:10:04,954 cisTarget    INFO     Annotating motifs for M2VsRest
(ctx_internal_ray pid=171608) 2022-11-01 14:10:08,144 cisTarget    INFO     Getting cistromes for M2VsRest
2022-11-01 14:10:12,720 cisTarget    INFO     Done!
2022-11-01 14:10:12,722 pycisTarget_wrapper INFO     /projects/marralab_prj/djin_marralab_prj/10X_Multiome/python/2022.10.26_SCENICplus/output/scATAC/motifs/CTX_DARs_All folder already exists.
2022-11-01 14:10:12,766 pycisTarget_wrapper INFO     Running cisTarget without promoters for DARs
2022-11-01 14:10:25,176 INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
(ctx_internal_ray pid=172447) 2022-11-01 14:10:30,633 cisTarget    INFO     Running cisTarget for M2VsRest which has 3013 regions
(ctx_internal_ray pid=172447) 2022-11-01 14:10:57,092 cisTarget    INFO     Annotating motifs for M2VsRest
(ctx_internal_ray pid=172447) 2022-11-01 14:10:59,785 cisTarget    INFO     Getting cistromes for M2VsRest
2022-11-01 14:11:02,366 cisTarget    INFO     Done!
2022-11-01 14:11:02,367 pycisTarget_wrapper INFO     /projects/marralab_prj/djin_marralab_prj/10X_Multiome/python/2022.10.26_SCENICplus/output/scATAC/motifs/CTX_DARs_No_promoters folder already exists.
2022-11-01 14:11:02,408 pycisTarget_wrapper INFO     Running DEM for DARs
2022-11-01 14:11:02,408 DEM          INFO     Reading DEM database
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/djin_prj/Installs/python_virtualenv/SCENICplus/scenicplus/src/scenicplus/wrappers/run_pycistarget.py", line 232, in run_pycistarget
    menr['DEM_'+key+'_All'] = DEM(dem_db = dem_db,
  File "/projects/djin_prj/Installs/python_virtualenv/SCENICplus/lib/python3.8/site-packages/pycistarget/motif_enrichment_dem.py", line 319, in __init__
    self.run(dem_db.db_scores, **kwargs)
  File "/projects/djin_prj/Installs/python_virtualenv/SCENICplus/lib/python3.8/site-packages/pycistarget/motif_enrichment_dem.py", line 349, in run
    # contrasts = [[(self.region_sets.keys()[0])],['Shuffle']]
TypeError: 'dict_keys' object is not subscriptable
```

**Version (please complete the following information):**
 - Python: 3.8.8
 - Pycistarget: '1.0.2.dev9+g0ed8289'

**Comment by SeppeDeWinter** [comment]
Hi @DHelix 

Sorry for the late reply.

You can not run the DEM algorithm with a single key-value pair. The reason is that DEM (*D*ifferential *e*nrichment of *m*otifs) is developed to find motifs which are differentially enriched between multiple sets of regions. 
Which will not work in your case where you only have a single set.

The cistarget algorithm will still work though.

To skip running DEM you can set `dem_db_path` to `None`.


Hope this helps.

Best,

Seppe

**Comment by DHelix** [comment]
Hi @SeppeDeWinter,
Thanks a lot for your reply! I see. I'll skip the DEM step.
Best,
Dan
