### ISSUE TITLE
Print proper error message when there is no overlap between BED file and cisTarget database.

### ISSUE THREAD

**Issue by ghuls** [aertslab/pycistarget#25]
**Is your feature request related to a problem? Please describe.**

When running `pycistarget cistarget` with a BED file where None of the chromosome names match (e.g. BED file is missing "chr"), it would be nice that a proper error message is displayed when the intersection/overlap gives an empty PyRanges object, instead of `"PyRanges object has no attribute X"`.

```python
pycistarget cistarget --cistarget_db_fname /resources/cistarget/dm6_v10_clust.regions_vs_motifs.rankings.feather --bed_fname epithelial_cell_0_logfc-2.bed --output_folder /tmp/tmp_cistarget --species dm
2023-10-02 14:29:58,506 cisTarget    INFO     Reading cisTarget database
Traceback (most recent call last):
  File "/lustre1/project/stg_00002/mambaforge/vsc34310/envs/cli_pycistarget/bin/pycistarget", line 33, in <module>
    sys.exit(load_entry_point('pycistarget', 'console_scripts', 'pycistarget')())
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/cli/pycistarget.py", line 586, in main
    args.func(args)
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/cli/pycistarget.py", line 69, in cistarget
    run_cistarget_command(
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/cli/commands.py", line 93, in run_cistarget_command
    ctx_db = cisTargetDatabase(
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/motif_enrichment_cistarget.py", line 56, in __init__
    self.regions_to_db, self.db_rankings, self.total_regions = self.load_db(fname,
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/motif_enrichment_cistarget.py", line 112, in load_db
    target_to_db = target_to_query(region_sets, list(db_regions), fraction_overlap = fraction_overlap)
  File "/lustre1/project/stg_00002/lcb/eceksi/user_software/pycistarget/src/pycistarget/utils.py", line 285, in target_to_query
    join_pr.Overlap_query =  join_pr.Overlap/(join_pr.End_b - join_pr.Start_b)
  File "/lustre1/project/stg_00002/mambaforge/vsc34310/envs/cli_pycistarget/lib/python3.8/site-packages/pyranges/pyranges.py", line 269, in __getattr__
    return _getattr(self, name)
  File "/lustre1/project/stg_00002/mambaforge/vsc34310/envs/cli_pycistarget/lib/python3.8/site-packages/pyranges/methods/attr.py", line 67, in _getattr
    raise AttributeError("PyRanges object has no attribute", name)
AttributeError: ('PyRanges object has no attribute', 'Overlap')
```

**Describe the solution you'd like**

```
pycistarget cistarget --cistarget_db_fname /resources/cistarget/dm6_v10_clust.regions_vs_motifs.rankings.feather --bed_fname epithelial_cell_0_logfc-2.bed --output_folder /tmp/tmp_cistarget --species dm
2023-10-02 14:29:58,506 cisTarget    INFO     Reading cisTarget database
2023-10-02 14:29:58,506 cisTarget    ERROR     Reading cisTarget database: No overlap found between BED file and cisTarget database. Check if chromosome names match.
```

**Comment by SeppeDeWinter** [comment]
https://github.com/aertslab/pycistarget/commit/d50c6f4eb8573e048cfc0fd7681da8d61ffd3a0f

Example output:

```python

2023-10-02 22:26:13,829 cisTarget    INFO     Reading cisTarget database
Traceback (most recent call last):
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/bin/pycistarget", line 8, in <module>
    sys.exit(main())
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/cli/pycistarget.py", line 586, in main
    args.func(args)
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/cli/pycistarget.py", line 69, in cistarget
    run_cistarget_command(
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/cli/commands.py", line 93, in run_cistarget_command
    ctx_db = cisTargetDatabase(
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/motif_enrichment_cistarget.py", line 56, in __init__
    self.regions_to_db, self.db_rankings, self.total_regions = self.load_db(fname,
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/motif_enrichment_cistarget.py", line 112, in load_db
    target_to_db = target_to_query(region_sets, list(db_regions), fraction_overlap = fraction_overlap)
  File "/data/users/sdewin/programs/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pycistarget/utils.py", line 286, in target_to_query
    raise ValueError(
ValueError:
            None of the regions in the bed file overlap with the cistarget database.
            Check wether the chromosome names of the input regions are correctly
            formatted and that you are using the correct database.

```
