### ISSUE TITLE
Indexing pandas data frame with set is deprecated

### ISSUE THREAD

**Issue by schae211** [aertslab/pycistarget#7]
In: https://github.com/aertslab/pycistarget/blob/67a17575c322d76317334eaf6135e8c619a66fee/pycistarget/motif_enrichment_cistarget.py#L299

`self.regions_to_db = ctx_db.regions_to_db[self.name] if type(ctx_db.regions_to_db) == dict else ctx_db.regions_to_db.loc[set(coord_to_region_names(self.region_set)) & set(ctx_db.regions_to_db['Target'])]`

I get the following error:

"Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead."

Using Pandas version 1.4.3 (the most recent version).

I guess you just have to wrap `list` around the set.

**Comment by SeppeDeWinter** [comment]
Hi @schae211 

We are aware of this warning message. 
Indeed converting to a list will solve it.

However, did the motif enrichment actually crash (normally it should just print the warning but continue running).

Best,

S

**Comment by schae211** [comment]
Hi @SeppeDeWinter 

I was looking into this https://github.com/aertslab/scenicplus/issues/27, and for a second I thought this issue here might have something to do with it. But this is not the case.

**Comment by SeppeDeWinter** [comment]
Hi @schae211 

Indeed, it's not the case.

Thank you for the nice bug report in https://github.com/aertslab/scenicplus/issues/27, I will take a look as soon as possible.

In the mean time I will close this issue.

Best 

S

**Comment by Gat2018** [comment]
I am constructing ancenstral state with pastml package and I got this error  any help please


/usr/local/lib/python3.8/dist-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Traceback (most recent call last):
  File "/home/manager/.local/bin/pastml", line 8, in <module>
    sys.exit(main())
  File "/home/manager/.local/lib/python3.8/site-packages/pastml/acr.py", line 1227, in main
    pastml_pipeline(**vars(params))
  File "/home/manager/.local/lib/python3.8/site-packages/pastml/acr.py", line 649, in pastml_pipeline
    _validate_input(tree, columns, name_column if html_compressed or html_mixed else None, data, data_sep, id_index,
  File "/home/manager/.local/lib/python3.8/site-packages/pastml/acr.py", line 865, in _validate_input
    filtered_df = df.loc[common_ids, :]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1091, in __getitem__
    check_dict_or_set_indexers(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 2611, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.

**Comment by SeppeDeWinter** [comment]
@Gat2018 

Could you please elaborate a bit more on what you are trying to do? 
I'm not familiar with the `pastml` package.

All the best,

Seppe

**Comment by Gat2018** [comment]
Hi, this model for ancestral state reconstruction (ASR)  ...pastml
-*p*hylogenetic
*a*nalysis with *s*pace and *t*ime *m*odel

We estimate the associations between pathogens and location and time

Gaspary

**Comment by SeppeDeWinter** [comment]
Okay, and with which part of the code do you get this error? Can you show which command you were running?

Best,

Seppe

**Comment by Gat2018** [comment]
Dear Seppe,

Yes, here is the command line and error I got attached

**Comment by SeppeDeWinter** [comment]
I don't see the text file, that is the issue. 

So if you could just copy-paste the command and error (as a comment to this github issue) I can try and help you.

**Comment by Gat2018** [comment]
Hi,

The command is

pastml -t For_Visualization_tree01.nwk -d tz_metadata2.csv -s , -i 1 -c
country  --prediction_method MPPA -o OUT_DATA --html HTML --html_compressed
HTML_COMPRESSED --verbose --upload_to_itol --itol_tree_name ITOL_TREE

The problem for -c country
-c flag indicates the column that i want to include in the analysis  so in
this case I have two columns in the csv file that looks like
name (index 0, first column that includes identifiers), country (index 1,
second column), date (index 2, third column for years (2010,2015, etc.....)

So my csv reads as       name,country,date (three columns)

When I want to include country and date in the analysis    -c country date
  it does not work  gives me this error  TypeError:float() argument must be
a string or a number not a set?
When I just include one column (country)  as -c country it does work well

So    with one column included  -c country   IT WORKS
        with two columns included -c county date  IT DOES NOT WORK
....gives  THIS TypeError:float() argument must be a string or a number not
a set?

**Comment by SeppeDeWinter** [comment]
Hi @Gat2018 

This issue is not related to pycistarget (the repo where you are posting your issue).
I guess you want to open an issue on the pastml repo https://github.com/evolbioinfo/pastml?

All the best,

Seppe
