### ISSUE TITLE
run_pycistarget: error in DEM for DARs

### ISSUE THREAD

**Issue by yamamotoryo** [aertslab/pycistarget#9]
**Describe the bug**
Thank you for the great software.
When I did run_pycistarget, I got the key error.
DEM for topics_ otsu and topic_top_3 worked but failed for DARs.
Looking at the results of CTX_DARs_ALL, all the region sets have enriched motifs (NES > 3).
According to the traceback, there seemed to be an error in making the contrast group. However, I couldn't understand what had happened. 
I appreciate it if you would give me any advice.

**To Reproduce**
```
run_pycistarget(
    region_sets = region_sets,
    species = 'homo_sapiens',
    save_path = os.path.join(work_dir, 'motifs'),
    ctx_db_path = rankings_db,
    dem_db_path = scores_db,
    path_to_motif_annotations = motif_annotation,
    run_without_promoters = False,
    n_cpu = 8,
    _temp_dir = os.path.join(work_dir, 'ray_spill'),
    annotation_version = 'v10nr_clust')
```
**Error output**
2022-10-05 12:19:30,491 pycisTarget_wrapper INFO     Created folder : /Users/ryosuke/SCENIC/motifs/CTX_DARs_All
2022-10-05 12:19:30,587 pycisTarget_wrapper INFO     Running DEM for DARs
2022-10-05 12:19:30,587 DEM          INFO     Reading DEM database
2022-10-05 12:19:41,941 DEM          INFO     Creating contrast groups
Traceback (most recent call last):

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'Chromosome'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/var/folders/59/cxr2yt4926jc95n5w2mtz32r0000gn/T/ipykernel_80665/276315112.py", line 1, in <module>
    run_pycistarget(

  File "/Users/jack/opt/bioinformatic_tool/scenicplus/src/scenicplus/wrappers/run_pycistarget.py", line 232, in run_pycistarget
    menr['DEM_'+key+'_All'] = DEM(dem_db = dem_db,

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycistarget/motif_enrichment_dem.py", line 319, in __init__
    self.run(dem_db.db_scores, **kwargs)

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycistarget/motif_enrichment_dem.py", line 365, in run
    region_groups = [create_groups(contrast = contrasts[x],

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycistarget/motif_enrichment_dem.py", line 365, in <listcomp>
    region_groups = [create_groups(contrast = contrasts[x],

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycistarget/motif_enrichment_dem.py", line 522, in create_groups
    fg_pr = coord_to_region_names(fg_pr_overlap[fg_pr_overlap.NumberOverlaps != 0])

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycistarget/utils.py", line 18, in coord_to_region_names
    return list(coord['Chromosome'].astype(str) + ':' + coord['Start'].astype(str) + '-' + coord['End'].astype(str))

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3631, in get_loc
    raise KeyError(key) from err

KeyError: 'Chromosome'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python 3.9.7
 - scenicplus 0.1.dev447+gd4fd733

**Comment by yamamotoryo** [comment]
Hi @cbravo93,

Thank you for the quick reply. I have clusters 0 –14. I think all the clusters have some region sets.
The cluster with the least regions was cluster 3, and it had only 21 rows.  

Best,
Ryosuke

In [208]:region_sets['DARs']
Out[208]: 
{'0': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 184792383 | 184792792 |
 | chr1         | 184882424 | 184882838 |
 | chr1         | 58934500  | 58934945  |
 | chr1         | 108716259 | 108716738 |
 | ...          | ...       | ...       |
 | chrX         | 123008865 | 123009434 |
 | chrX         | 77019062  | 77019439  |
 | chrX         | 50108335  | 50108634  |
 | chrX         | 99113410  | 99113937  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 392 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '1': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 214203045 | 214203328 |
 | chr1         | 88029811  | 88030183  |
 | chr2         | 52702807  | 52703265  |
 | chr2         | 144349679 | 144350024 |
 | ...          | ...       | ...       |
 | chr2         | 66227872  | 66228575  |
 | chr1         | 214203045 | 214203328 |
 | chr20        | 39985843  | 39986685  |
 | chr20        | 10720454  | 10720882  |
 | chr20        | 6192837   | 6193528   |
 | chr20        | 13130024  | 13130429  |
 | chrX         | 132848203 | 132848584 |
 | chrX         | 144627803 | 144628280 |
 | chrY         | 13728884  | 13729320  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 69 rows and 3 columns from 21 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '10': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 40915005  | 40915204  |
 | chr1         | 165137627 | 165138212 |
 | chr1         | 62299883  | 62300087  |
 | chr1         | 180594822 | 180595200 |
 | ...          | ...       | ...       |
 | chrX         | 119870638 | 119872326 |
 | chrX         | 13669160  | 13669585  |
 | chrX         | 153226132 | 153226830 |
 | chrX         | 12804420  | 12805086  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 2,680 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '11': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 40915005  | 40915204  |
 | chr1         | 165137627 | 165138212 |
 | chr1         | 62299883  | 62300087  |
 | chr1         | 62285279  | 62285930  |
 | ...          | ...       | ...       |
 | chrX         | 15269487  | 15270373  |
 | chrX         | 404024    | 404622    |
 | chrX         | 13669160  | 13669585  |
 | chrX         | 154012360 | 154013059 |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 2,815 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '12': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 34380545  | 34381023  |
 | chr1         | 27875174  | 27875506  |
 | chr1         | 110756258 | 110756790 |
 | chr1         | 211712601 | 211712989 |
 | ...          | ...       | ...       |
 | chrX         | 676742    | 676945    |
 | chrX         | 43881757  | 43882663  |
 | chrX         | 102832397 | 102833025 |
 | chrX         | 20116222  | 20117085  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 14,399 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '13': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 44208052  | 44208450  |
 | chr1         | 95541750  | 95542076  |
 | chr1         | 90577183  | 90577695  |
 | chr1         | 74599338  | 74599815  |
 | ...          | ...       | ...       |
 | chrX         | 10119145  | 10120015  |
 | chrX         | 41252969  | 41254127  |
 | chrX         | 107825435 | 107827005 |
 | chrX         | 47381649  | 47382501  |
 | chrY         | 15455553  | 15456507  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 15,310 rows and 3 columns from 24 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '14': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 225417159 | 225417358 |
 | chr1         | 73988352  | 73988736  |
 | chr1         | 172513462 | 172513776 |
 | chr1         | 205090043 | 205090525 |
 | ...          | ...       | ...       |
 | chrX         | 150872908 | 150873325 |
 | chrX         | 47192937  | 47193951  |
 | chrX         | 7926850   | 7927886   |
 | chrX         | 53256335  | 53257475  |
 | chrY         | 15455553  | 15456507  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 13,628 rows and 3 columns from 24 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '2': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 163533693 | 163534216 |
 | chr1         | 220290108 | 220290436 |
 | chr1         | 200320774 | 200321491 |
 | chr1         | 167158044 | 167158592 |
 | ...          | ...       | ...       |
 | chrX         | 145821171 | 145821578 |
 | chrX         | 8900191   | 8900590   |
 | chrX         | 43969557  | 43969914  |
 | chrX         | 133770967 | 133771470 |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 225 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '3': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr2         | 207397867 | 207398252 |
 | chr2         | 128562907 | 128563668 |
 | chr3         | 99439643  | 99440136  |
 | chr4         | 27055204  | 27055562  |
 | ...          | ...       | ...       |
 | chr4         | 175376112 | 175376582 |
 | chr2         | 207397867 | 207398252 |
 | chr15        | 51144174  | 51144457  |
 | chr15        | 98391163  | 98391534  |
 | chr20        | 39115275  | 39115728  |
 | chrX         | 144627803 | 144628280 |
 | chrY         | 13728884  | 13729320  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 21 rows and 3 columns from 15 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '4': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 44208052  | 44208450  |
 | chr1         | 95541750  | 95542076  |
 | chr1         | 74599338  | 74599815  |
 | chr1         | 90577183  | 90577695  |
 | ...          | ...       | ...       |
 | chrX         | 7926850   | 7927886   |
 | chrX         | 54950303  | 54951504  |
 | chrX         | 69503566  | 69505187  |
 | chrX         | 44343033  | 44343940  |
 | chrY         | 15455553  | 15456507  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 15,403 rows and 3 columns from 24 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '5': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 182556260 | 182556599 |
 | chr1         | 107692625 | 107693278 |
 | chr1         | 73988352  | 73988736  |
 | chr1         | 225417159 | 225417358 |
 | ...          | ...       | ...       |
 | chrX         | 47192937  | 47193951  |
 | chrX         | 10728510  | 10729360  |
 | chrX         | 7926850   | 7927886   |
 | chrX         | 11427192  | 11428128  |
 | chrY         | 15455553  | 15456507  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 14,434 rows and 3 columns from 24 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '6': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 163533693 | 163534216 |
 | chr1         | 200320774 | 200321491 |
 | chr1         | 214227352 | 214227944 |
 | chr1         | 167158044 | 167158592 |
 | ...          | ...       | ...       |
 | chrX         | 17634717  | 17635555  |
 | chrX         | 675570    | 676341    |
 | chrX         | 79366778  | 79367558  |
 | chrX         | 93783239  | 93784136  |
 | chrY         | 13728884  | 13729320  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 2,747 rows and 3 columns from 24 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '7': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 185789948 | 185790386 |
 | chr1         | 60430152  | 60430648  |
 | chr1         | 166184725 | 166185203 |
 | chr1         | 245298668 | 245299077 |
 | ...          | ...       | ...       |
 | chrX         | 31508338  | 31508955  |
 | chrX         | 152642926 | 152643582 |
 | chrX         | 123008865 | 123009434 |
 | chrX         | 123526282 | 123526953 |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 1,726 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '8': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 185789948 | 185790386 |
 | chr1         | 166184725 | 166185203 |
 | chr1         | 60430152  | 60430648  |
 | chr1         | 6525540   | 6525804   |
 | ...          | ...       | ...       |
 | chrX         | 34624303  | 34624760  |
 | chrX         | 50108335  | 50108634  |
 | chrX         | 99113410  | 99113937  |
 | chrX         | 137100303 | 137100995 |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 216 rows and 3 columns from 23 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.,
 '9': +--------------+-----------+-----------+
 | Chromosome   | Start     | End       |
 | (category)   | (int32)   | (int32)   |
 |--------------+-----------+-----------|
 | chr1         | 58934500  | 58934945  |
 | chr2         | 196725966 | 196726231 |
 | chr2         | 21382808  | 21383263  |
 | chr2         | 211509562 | 211510068 |
 | ...          | ...       | ...       |
 | chr1         | 58934500  | 58934945  |
 | chr18        | 10386019  | 10386457  |
 | chr18        | 40012918  | 40013575  |
 | chr21        | 29748665  | 29749112  |
 | chrX         | 99113410  | 99113937  |
 +--------------+-----------+-----------+
 Unstranded PyRanges object has 37 rows and 3 columns from 17 chromosomes.
 For printing, the PyRanges was sorted on Chromosome.}

**Comment by yamamotoryo** [comment]
Yes, that's right. I had an error even if I set the ```run_without_promoters = False```.
I guess something happened when creating the contrast groups.

Ryosuke

**Comment by yamamotoryo** [comment]
Thank you so much for your help. Removing the cluster 3 and 9 worked well!!

Thank you,
Ryosuke
